### ISSUE TITLE
Integer overflow in `maps.HealpixSkyMap.angle_to_pixel` for `nside` = 16384

### ISSUE THREAD

**Issue by ndhuang** [CMB-S4/spt3g_software#119]
```
m = maps.HealpixSkyMap(16384)
m.angle_to_pixel(0, -pi / 2)
>>> 18446744073709551615
```

**Comment by arahlin** [comment]
This issue stems from using int32 for all of the math.  There are int64 versions of all the chealpix functions, but `HealpixSkyMapInfo` class probably needs some TLC to make sure that all of the internal functions there are using int64 as well.
