### ISSUE TITLE
Ellipsis for repr of vector

### ISSUE THREAD

**Issue by mhasself** [CMB-S4/spt3g_software#23]
numpy repr of long arrays is abbreviated:
```
>>> numpy.zeros(10000)
array([0, 0, 0, ..., 0, 0, 0])
```
But G3Vector types just print every single element, making it easy to flood an interactive session with pages of unwanted output.  Is there any objection to implementing a similar abbreviation in vec_repr?  Since repr does not use Description(), the latter could continue to present a complete dump of the vector, in case that's needed.

**Comment by arahlin** [comment]
No objection, please do!

**Comment by nwhitehorn** [comment]
Ellipses would be great.

I'm a bit confused by the problem description, though. G3Vector types don't print all their elements unless they have fewer than 5 elements (see G3Vector's Summary() method, which is what repr() calls). Instead, they just print the number of elements (which is strictly worse than compression with an ellipsis). Where are you seeing it dump everything?

**Comment by mhasself** [comment]
Ya... repr doesn't access Summary, for vectors.  It's attached to pybindings.h:vec_repr().

**Comment by mhasself** [comment]
Addressed in #24 .  Thanks!
