### ISSUE TITLE
Arithmetic broken for G3 numeric types

### ISSUE THREAD

**Issue by ndhuang** [CMB-S4/spt3g_software#83]
G3 numeric types (and their vector equivalents) all seem to have some broken arithmetic operations, either with numpy and python scalars, or even with themselves.  Here is a sampling of things that raise `TypeError: unsupported operand...`:
```
G3Int + G3Int
int + G3Int
G3Int + int
G3VectorInt + int
G3VectorDouble + G3VectorDouble
float * G3VectorDouble
float + G3VectorDouble
G3VectorDouble + float
G3VectorComplexDouble * float
```
Notably, the follwing do work:
```
np.float64 * G3VectorDouble
G3VectorDouble * np.float64
G3VectorDouble * float
G3VectorComplexDouble * float64
```

**Comment by arahlin** [comment]
I suspect this is not easy to resolve.  You can work around the issue by using `np.asarray()` on `G3VectorInt` and `G3VectorDouble` objects for now, since the result is a view on the underlying shared memory buffer.
